name: Studio Release
on:
  release:
    types:
      - published
jobs:
  call-workflow:
    uses: vesoft-inc/nebula-studio/.github/workflows/build.yml@master
    secrets:
      oss_endpoint: ${{ secrets.OSS_ENDPOINT }}
      oss_id: ${{ secrets.OSS_ID }}
      oss_secret: ${{ secrets.OSS_SECRET }}
      oss_url: ${{ secrets.OSS_URL }}
      ga_id: ${{ secrets.GA_ID }}
  docker-image:
    name: docker image build
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout Github Action
      uses: actions/checkout@master
    - 
      name: set track
      run: bash ./scripts/setEventTracking.sh ${{ secrets.GA_ID }}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Build
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: vesoft/nebula-graph-studio:v3.2.1